### ISSUE TITLE
fofn example

### ISSUE THREAD

**Issue by angelovangel** [moold/kseq-rs#16]
I can't get `parse_path` to work with fofn. It reads the first record only in every file.
Could you give an example?

**Comment by moold** [comment]
1. Let's say you have 3 fa/fq files: file1.fasta, file2.fastq.gz, file3.fastq
2. Then  create a `fofn` file: `ls file1.fasta file2.fastq.gz file3.fastq > files.fofn`;
3. And use `kseq-rs` to prase `files.fofn`:
```
let mut records = parse_path(files.fofn).unwrap();
while let Some(record) = records.iter_record().unwrap() {
println!("head:{} des:{} seq:{} qual:{} len:{}", 
	record.head(), record.des(), record.seq(), 
	record.qual(), record.len());
	}
```

**Comment by moold** [comment]
Could you try to use the latest version `kseq = "0.5.1"` and then using the example code I provided to check  if it is working properly correctly?

**Comment by angelovangel** [comment]
I did run with the example code. I see the same behaviour.
I used a fofn with paths to 2 files with ~ 1 milion reads each. Only 350 reads are printed if I use the fofn, and all reads are printed if I pass the fastq file directly.

**Comment by moold** [comment]
en...., It seems impossible, because the functions to iterate echo record are the same, and I used kseq in many projects and no unusual issues found. So could you share your input files, so I can try to analyze what the problem is?

**Comment by angelovangel** [comment]
Here are two files, I tried other files too with the same result.
https://www.dropbox.com/scl/fo/yycjgxtisfwjx21xsb13w/h?rlkey=bui56lqgvxy2z0ssh45nt7v11&dl=0

**Comment by moold** [comment]
Yes, you are right, and I think you can try to update `kseq` to `kseq = "0.5.2"`, which should solve this problem.

**Comment by angelovangel** [comment]
Works now:)
Thanks!
